[package]
name = "project_euler"
version = "0.1.0"
authors = ["Lucas Wiman <lucaswiman@counsyl.com>"]
edition = "2021"

[dependencies]
lazy_static = "0.1.*"
hyper = "*"
reqwest = "0.11"
scraper = "0.12"
tokio = { version = "1", features = ["full"] }
html2text = "0.1"
